-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:36:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `Course_Number` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `credits` INT NULL,
  `syllabus` VARCHAR(45) NULL,
  `Prerequisites` VARCHAR(45) NULL,
  PRIMARY KEY (`Course_Number`))
ENGINE = MRG_MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructor` (
  `instructor_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Department` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_offering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_offering` (
  `course_id` INT NOT NULL,
  `year` INT NULL,
  `semester` INT NULL,
  `section_number` INT NULL,
  `instructor_id` INT NULL,
  `timings` VARCHAR(45) NULL,
  `classRoom` VARCHAR(45) NULL,
  PRIMARY KEY (`course_id`),
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Course` (`Course_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instructor_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Instructor` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `program`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
